# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rockets_time_table',
            old_name='user',
            new_name='launching_time',
        ),
    ]
