# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20181008_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_time_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='rockets` image'),
        ),
    ]
