# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rockets_time_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_time_table',
            name='descrption',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='rockets_time_table',
            name='mission',
            field=models.CharField(default='', max_length=500),
        ),
    ]
