# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20181009_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_time_table',
            name='mission_url',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
